spring.application.name=e-commerce
server.port=8080

#server.servlet.context-path = url

# propiedades para datasources
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:ecommerce_progra2_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# propiedades para jpa
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# propiedades para logger
logging.level.root=info
logging.level.com.ae.app.three=debug

logging.level.org.springframework.web=info

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace