spring.application.name=mock-gateway-api
server.port=8081

logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.sv.grupo1.ecommerce.gateway=DEBUG

logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%15.15t]){faint} %clr([traceId:%X{traceId:-N/A}]){magenta} %clr(%-40.40logger{39}){cyan} : %m%n

logging.file.name=mock-gateway-api/logs/gateway-transactions.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7