-- Migración: hace que id_producto se autogenere, igual que ya hacen
-- pedidos, detalles_pedido, pagos, envios y movimientos_inventario
-- (GENERATED BY DEFAULT AS IDENTITY).
--
-- Producto.java declara idProducto como @GeneratedValue(strategy = IDENTITY),
-- pero schema-ecommerce.sql lo dejó como "integer PRIMARY KEY" simple, sin
-- generación automática. Al guardar un producto nuevo, Hibernate no manda
-- el id (espera que la base lo genere) y Postgres rechaza el NULL en la
-- primary key.
--
-- Correr una sola vez, después de schema-ecommerce.sql (y del seed, si ya
-- se cargó): reutiliza los ids existentes y arranca la secuencia después
-- del máximo actual.
--   psql -U <usuario> -h localhost -d <base_de_datos> -f db/migracion-productos-id-identity.sql

ALTER TABLE core.productos ALTER COLUMN id_producto ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
  pg_get_serial_sequence('core.productos', 'id_producto'),
  COALESCE((SELECT MAX(id_producto) FROM core.productos), 0)
);
