-- Migración: Creación de tabla para gestionar múltiples imágenes por producto.
-- Relación 1:N (Un producto puede tener muchas imágenes).

CREATE TABLE "core"."productos_imagenes" (
  "id_imagen" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" integer NOT NULL,
  "url_imagen" varchar NOT NULL,
  "es_principal" boolean DEFAULT false, -- Ayuda para saber si es la imagen principal
  "orden" integer DEFAULT 0, -- Ayuda para controlar el orden de las imágenes
  "fecha_creacion" timestamp DEFAULT (now())
);

-- Llave foránea para vincular la imagen al producto
ALTER TABLE "core"."productos_imagenes" 
  ADD CONSTRAINT fk_imagenes_producto 
  FOREIGN KEY ("id_producto") 
  REFERENCES "core"."productos" ("id_producto") 
  ON DELETE CASCADE; -- Si borran el producto, sus imágenes desaparecen de la BD

-- Comentarios documentando la tabla
COMMENT ON TABLE "core"."productos_imagenes" IS 'Almacena la galería de imágenes de cada producto';
COMMENT ON COLUMN "core"."productos_imagenes"."es_principal" IS 'Solo una imagen por producto debería ser TRUE. Será la portada.';
