-- Migración para optimizar y depurar las tablas "marcas" y "categorias".
-- Aplica los identity faltantes, corrige errores ortográficos y añade la
-- columna "estado" para borrado lógico (soft deletes).

-- 1. TABLA "catalogo"."marcas"
-- Hacer que id_marca se autogenere
ALTER TABLE catalogo.marcas ALTER COLUMN id_marca ADD GENERATED BY DEFAULT AS IDENTITY;

-- Evitar marcas duplicadas
ALTER TABLE catalogo.marcas ADD CONSTRAINT marcas_nombre_marca_key UNIQUE (nombre_marca);

-- Agregar estado para borrado lógico
ALTER TABLE catalogo.marcas ADD COLUMN estado char DEFAULT 'A';

-- 2. TABLA "core"."categorias"
-- Hacer que id_categoria se autogenere
ALTER TABLE core.categorias ALTER COLUMN id_categoria ADD GENERATED BY DEFAULT AS IDENTITY;

-- Corregir el typo "descripccion" a "descripcion"
ALTER TABLE core.categorias RENAME COLUMN descripccion TO descripcion;

-- Agregar estado para borrado lógico
ALTER TABLE core.categorias ADD COLUMN estado char DEFAULT 'A';

-- 3. TABLA "core"."productos" (Extra)
-- Para blindar el stock y evitar inventario negativo, aplicamos el constraint CHECK
ALTER TABLE core.productos ADD CONSTRAINT productos_stock_disponible_check CHECK (stock_disponible >= 0);
